export const firstName = {
    'Albania': [
        'Noel',
        'Joel',
        'Mateo',
        'Ergi',
        'Luis',
        'Aron',
        'Samuel',
        'Roan',
        'Roel',
        'Xhoel'
    ],
    'England': [
        'Vincent',
        'Kai',
        'Frankie',
        'Nico',
        'Calvin',
        'Arlo',
        'Teddie',
        'Kieran',
        'Adam',
        'Freddy',
        'Harrison',
        'Daniel',
        'Quinn',
        'Hugh',
        'Rufus',
        'Raphael',
        'Raphael',
        'Maxwell',
        'Bradley',
        'Maximilian',
    ],
    'USA': [
        'Joseph',
        'Charles',
        'Frankie',
        'Max',
        'Charlie',
        'Tyson',
        'Rogelio',
        'Darius',
        'Byron',
        'Kolby',
        'Bailey',
        'Aaron',
        'Ryan',
        'Callum',
        'Reece',
        'Jonathan',
        'Jasper',
        'Nehemiah',
        'Braeden',
        'Titus',
    ],
    'China': [
        'Xiang',
        'Wu',
        'Zhao',
        'Liu',
        'Xiong',
        'Li',
        'Feng',
        'Sun',
        'Yang',
        'Xiao',
        'Zou',
        'Lai',
        'Zeng',
        'Bai',
        'Liu',
        'Xian',
        'Geng',
        'Kong',
        'Wan',
        'Xiang',
    ],
    'Greece': [
        'Haris',
        'Iasonas',
        'Aristotelis',
        'Aristidis',
        'Panikos',
        'Serapheim',
        'Stergios',
        'Eros',
        'Iordanis',
        'Myron',
        'Vassilios',
        'Miron',
        'Periklis',
        'Aggelos',
        'Yorgos',
        'Prokopos',
        'Minos',
        'Kiriakos',
        'Spiro',
        'Lambros',
    ],
    'Russia': [
        'Fomin',
        'Konyakov',
        'Kubyshkin',
        'Grekov',
        'Ryzhanov',
        'Khodyayev',
        'Ilyushin',
        'Rabrenovich',
        'Polachev',
        'Yumashev',
        'Dernov',
        'Balakirev',
        'Annikov',
        'Chupakhin',
        'Savasin',
        'Pokrovsky',
        'Belinsky',
        'Glukhov',
        'Kirilishen',
        'Koshelev',
    ],
    'Algeria': [
        'Mohamed',
        'Abdelkader',
        'Ahmed',
        'Mohammed',
        'Ali',
        'Rachid',
        'Said',
        'Brahim',
        'Omar',
        'Djamel'
    ],
    'Argentina': [
        'Santiago',
        'Mateo',
        'Juan',
        'Matías',
        'Nicolás',
        'Benjamín',
        'Pedro',
        'Tomás',
        'Thiago',
    ],
    'Australia': [
        'Oliver',
        'William',
        'Jack',
        'Noah',
        'Thomas',
        'Lucas',
        'James',
        'Alex',
        'Alexander',
        'Ethan',
    ],
    'Austria': [
        'Lukas',
        'Maximilian',
        'Jakob',
        'David',
        'Tobias',
        'Paul',
        'Jonas',
        'Felix',
        'Alexander',
        'Elias',
    ],
    'Azerbaijan': [
        'Yusif',
        'Ali',
        'Omar',
        'Huseyn',
        'Mahammad',
        'Murad',
        'Aykhan',
        'Ughur',
        'Ibrahim',
        'Tunar',
    ],
    'Belgium': [
        'Lucas',
        'Louis',
        'Noah',
        'Nathan',
        'Adam',
        'Arthur',
        'Mohamed',
        'Victor',
        'Mathis',
        'Liam',
    ],
    'Brazil': [
        'Miguel',
        'Arthur',
        'Davi',
        'Heitor',
        'Gabriel',
        'Bernardo',
        'Lorenzo',
        'João',
        'Miguel',
        'Enzo',
        'Gabriel',
        'Pedro',
        'Henrique',
    ],
    'France': [
        'Ladislas ',
        'Constantin ',
        'Basile',
        'Émilien ',
        'Jean-Guy ',
        'Timothé ',
        'Fabien ',
        'Constantin ',
        'Maxime ',
        'Samuel ',
    ],
    'Germany': [
        'Tizian',
        'Nils',
        'Steffen',
        'Gert',
        'Oskar',
        'Cäsar',
        'Meik',
        'Gunter',
        'Maximilian',
        'Ruprecht',
    ],
    'Italy': [
        'Girardo',
        'Giovanni',
        'Ambrogio',
        'Marolo',
        'Elvezio',
        'Silvano',
        'Attilio',
        'Esuperio',
        'Bruto',
        'Vulpiano',
    ],
    'Iran': [
        'Amin',
        'Hossein',
        'Kazem',
        'Soroosh',
        'Peyman',
        'Mehran',
        'Amir Mohammad',
        'Changiz',
        'Behrouz',
        'Sirvan',
        'Homayoun',
        'Qobad',
        'Sahand',
        'Mamad',
        'Vahid',
        'Rostam',
        'Benyamin',
        'Mehdi',
        'Yashar',
        'Latif',
    ],
    'Turkey': [
        'Eraydin',
        'Alpar',
        'Tumkor',
        'Seda',
        'Ali Riza',
        'Okay',
        'Tor',
        'Apak',
        'Tozun',
        'Soylu',
        'Ergor',
        'Uzay',
        'Erdener',
        'Dinc',
        'Ayyildiz',
        'Vedat',
        'Kaner',
        'Tezal',
        'Goktug',
        'Hayri',
    ],
    'Japan': [
        'Hirota',
        'Kurosawa',
        'Kawamura',
        'Murano',
        'Hino',
        'Sakane',
        'Hori',
        'Yoshikawa',
        'Edamitsu',
        'Komuro',
        'Seto',
        'Hashi',
        'Saito',
        'Amari',
        'Sanda',
        'Fujimura',
        'Ishikura',
        'Kawada',
        'Oshita',
        'Shinsato',
    ],
    'KoreaSouth': [
        'Sa',
        'Chon',
        'Song',
        'Choe',
        'Kong',
        'Mangjol',
        'Chang',
        'In',
        'Ryuk',
        'Pu',
        'Chegal',
        'Yu',
        'Park',
        'Sonu',
        'Yang',
        'Tang',
        'Chu',
        'Kum',
        'Che',
        'Kum',
    ],
    'Iraq': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Saudi Arabia': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Qatar': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'UAE': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Egypt': [
        'Ahmad',
        'Kafele',
        'Nader',
        'Abdelrahman',
        'Nassor',
        'Assem',
        'Mahmoud',
        'Barika',
        'Bebti',
        'Hassan',
        'Adham',
        'Mamdoh',
        'Marwan',
        'Hosni',
        'Karim',
        'Aymn',
        'Aly',
        'Kamuzu',
        'Ismael',
    ],
    'Spain': [
        'Gael',
        'Franco',
        'Zacarías',
        'Saúl',
        'Macos',
        'Eduard',
        'Jonathan',
        'Christian',
        'Samuel',
        'Iker',
        'Alfredo',
        'Luis',
        'Nicolás',
        'Jose',
        'Mauric',
        'Lautaro',
        'Aaron',
        'Vicent',
        'Emiliano',
        'Juan',
    ],
    'Mexico': [
        'Gael',
        'Franco',
        'Zacarías',
        'Saúl',
        'Macos',
        'Eduard',
        'Jonathan',
        'Christian',
        'Samuel',
        'Iker',
        'Alfredo',
        'Luis',
        'Nicolás',
        'Jose',
        'Mauric',
        'Lautaro',
        'Aaron',
        'Vicent',
        'Emiliano',
        'Juan',
    ],
    'Portugal': [
        'Fred',
        'Leopoldo',
        'Gustavo',
        'André',
        'Ernesto',
        'Artur',
        'Heliodoro',
        'Ismael',
        'Rogério',
        'Tadeu',
        'Feliciano',
        'Isaac',
        'Ângelo',
        'Luís',
        'Victor',
        'Cristóvão',
        'Régulo',
        'Raul',
        'Kévim',
        'Noah',
    ],
    'Nigeria': [
        'Yobachukwu',
        'Chydi',
        'Nkechi',
        'Ebele',
        'Jaja',
        'Okparra',
        'Madukaife',
        'Ugoorji',
        'Uwaezuoke',
        'Ijendu',
        'Okpara',
        'Uzochi',
        'Okeke',
        'Chydea',
        'Okparra',
        'Chimaijem',
        'Chikere',
        'Chidiebere',
        'Chidey',
        'Madu',
    ],
    'Croatia': [
        'Zvonko',
        'Siniša',
        'Josip',
        'Andrija',
        'Ljubomir',
        'Alan',
        'Denis',
        'Zoran',
        'Ivan',
        'Dalibor',
        'Gordan',
        'Dinko',
        'Mislav',
        'Teo',
        'Božo',
        'Robert',
        'Kristijan',
        'Ilija',
        'Zdenko',
        'David',
    ],
    'Czech Republic': [
        'Roland',
        'Dalimil',
        'Kristián',
        'Gabriel',
        'Teodor',
        'Mikuláš',
        'Radovan',
        'Karel',
        'Radim',
        'Herbert',
        'Štefan',
        'Vojtěch',
        'Kamil',
        'Jiří',
        'Svatoslav',
        'Jan',
        'Miloslav',
        'Věnceslav',
        'Oliver',
        'Václav',
    ],
    'Denmark': [
        'Mogens',
        'David',
        'Torsten',
        'Ebbe',
        'Lauritz',
        'Elmer',
        'Bruno',
        'Freddy',
        'Jan',
        'Jannik',
        'Nikolaj',
        'Albert',
        'Nicolai',
        'Tim',
        'Egon',
        'Tim',
        'Christian',
        'Claus',
        'Nis',
        'Laust',
        'Arnold',
        'Patrick',
        'Axel',
        'Sonny',
        'Knud',
        'Markus',
        'David',
        'Sonny',
        'Thorkild',
        'Fritz',
    ],
    'Netherlands': [
        'Aart',
        'Daan',
        'Henkjan',
        'Joep',
        'Klaas',
        'Noud',
        'Lodewijk',
        'Coen',
        'Dirk',
        'Diederick',
        'Rudie',
        'Gijsje',
        'Marthijn',
        'Maurits',
        'Govert',
        'Hermen',
        'Jan',
        'Ewoud',
        'Twan',
        'Kees',
        'Maurits',
        'Mannes',
        'Emiel',
        'Nard',
        'Arnout',
        'Elco',
        'Corneel',
        'Nelis',
    ],
    'Poland': [
        'Hanusz ',
        'Wojsław ',
        'Kanimir ',
        'Roman ',
        'Lesław ',
        'Bogusław ',
        'Szymon ',
        'Alfons ',
        'Walentyn ',
        'Florentyn ',
        'Konstantyn ',
        'Ksawery ',
        'Donat ',
        'Klemens ',
        'Apoloniusz ',
        'Jaromir ',
        'Fryderyk ',
        'Rafał ',
        'Krzysztof ',
        'Leonard ',
        'Aleksy ',
        'Przemysł ',
        'Ziemowit ',
        'Żelisław ',
        'Onufry ',
        'Jozafat ',
        'Filip ',
        'Brunon ',
        'Antonius ',
        'Ryszard ',
    ],
    'Serbia': [
        'Gojko',
        'Gabrijel',
        'Slavoljub',
        'Jezdimir',
        'Milić',
        'Živko',
        'Teodor',
        'Staniša',
        'Života',
        'Milić',
        'Jakov',
        'Dobroslav',
        'Sretomir',
        'Vidak',
        'Grigorije',
        'Branko',
        'Vitomir',
        'Adam',
        'Saša',
        'Milan',
        'Stanimir',
        'Nenad',
        'Arsenije',
        'Tihomir',
        'Mijat',
        'Bogdan',
        'Filotije',
        'Danko',
        'Lubomir',
        'Mileta',
    ],
    'Uruguay': [
        'Israel',
        'Juan',
        'Jesús',
        'Armando',
        'Anthony',
        'Felipe',
        'Mariano',
        'Felix',
        'Antonio',
        'Roberto',
        'Luis',
        'Alonso',
        'Serafín',
        'Ian',
        'Lorenzo',
        'Isidoro',
        'Álvaro',
        'Valentín',
        'Diego',
        'Saúl',
        'Nicolás',
        'Mateo',
        'Jaime',
        'Jonatán',
        'Manuel',
        'Patricio',
        'Diego',
        'Rafael',
        'Jonathan',
        'Raul',
    ],
    'Ukraine': [
        'Andrij',
        'Orest',
        'Taras',
        'Panas',
        'Illya',
        'Vadym',
        'Valerij',
        'Anatolij',
        'Kazymyr',
        'Havrylo',
        'Arkadij',
        'Stepan',
        'Josyp',
        'Svyatoslav',
        'Taras',
        'Pylyp',
        'Pavlo',
        'Henadij',
        'Vladyslav',
        'Eduard',
        'Viktor',
        'Hryhorij',
        'Myron',
        'Panas',
        'Orest',
        'Taras',
        'Artem',
        'Kuzma',
        'Anatolij',
        'Petro',
    ]
};