export const teamNames = [
    'ManUtd',
    'ManCity',
    'Arsenal',
    'Chelsea',
    'Tottenham',
    'Liverpool',
    'WestHam',
    'Leicester',
    'Barcelona',
    'R.Madrid',
    'Atletico',
    'Bayern',
    'Dortmund',
    'Schalke04',
    'Leverkusen',
    'Juventus',
    'A.C.Milan',
    'Roma',
    'Inter',
    'Napoli',
    'PSG',
    'Lyonnais',
    'Marseille',
    'Monaco',
    'Shakhtar',
    'Benfica',
    'Porto',
    'Sporting',
    'Ajax',
    'Feyenoord',
    'PSV',
];

export const countries = [
    'Albania',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaijan',
    // 'Belarus',
    'Belgium',
    // 'Bolivia',
    // 'Bosnia',
    'Brazil',
    // 'Bulgaria',
    // 'Cameroon',
    // 'Chile',
    // 'China',
    // 'Colombia',
    // 'Costa Rica',
    // 'Cote d’Ivoire',
    // 'Croatia',
    // 'Cuba',
    // 'Czech Republic',
    // 'Denmark',
    // 'Ecuador',
    // 'Egypt',
    // 'Finland',
    // 'France',
    // 'Georgia',
    // 'Germany',
    // 'Ghana',
    // 'Greece',
    // 'Guatemala',
    // 'Honduras',
    // 'Hungary',
    // 'Iceland',
    // 'Iran',
    // 'Iraq',
    // 'Ireland',
    // 'Israel',
    // 'Italy',
    // 'Jamaica',
    // 'Japan',
    // 'Kazakhstan',
    // 'Kenya',
    // 'KoreaSouth',
    // 'Kosovo',
    // 'Latvia',
    // 'Mali',
    // 'Mexico',
    // 'Montenegro',
    // 'Morocco',
    // 'Netherlands',
    // 'New Zealand',
    // 'Nigeria',
    // 'Norway',
    // 'Panama',
    // 'Paraguay',
    // 'Peru',
    // 'Poland',
    // 'Portugal',
    // 'Qatar',
    // 'Romania',
    // 'Russia',
    // 'Saudi Arabia',
    // 'Senegal',
    // 'Serbia',
    // 'Slovakia',
    // 'Slovenia',
    // 'South Africa',
    // 'Spain',
    // 'Sweden',
    // 'Switzerland',
    // 'Tunisia',
    // 'Turkey',
    // 'Ukraine',
    // 'UAE',
    // 'USA',
    // 'Uruguay',
    // 'Uzbekistan',
    // 'Venezuela'
];

export const lastName = {
    'Azerbaijan': [
        'Mammadov',
        'Aliyev',
        'Hasanov',
        'Huseynov',
        'Guliyev',
        'Hajiyev',
        'Rasulov',
        'Suleymanov',
        'Musayev',
        'Abbasov',
        'Babayev',
        'Valiyev',
        'Orujov',
        'Ismayilov',
        'Ibrahimov',
    ],
    'Albania': [
        'Agani',
        'Ajeti',
        'Bajramovic',
        'Bardici',
        'Bejko',
        'Ciftja',
        'Culaj',
        'Dedej',
        'Dreshaj',
        'Elezi',
        'Fazliu',
        'Galica',
        'Gecaj',
        'Halili',
        'Hamza',
        'Hasani',
        'Haxhiu',
        'Meshkalla',
        'Rexhepi',
        'Rugova',
        'Salihu',
        'Shulku',
        'Simaku',
    ],
    'Algeria': [
        'Alloula',
        'Boutella',
        'Djermouni',
        'Khalef',
        'Benlabed',
        'Litim',
        'Belghoul',
        'Benyamina',
        'Partyka',
        'Mammeri',
    ],
    'Argentina': [
        'Toscano',
        'Russo',
        'Iadanza',
        'Benítez',
        'Manfrin',
        'Ávila',
        'Toledo',
        'Núñez',
        'Ferrari',
        'Lucciano',
    ],
    'Australia': [
        'Jackman',
        'Clark',
        'McKenzie',
        'Bishop',
        'Mitchell',
        'Simpson',
        'Ward',
        'Hamilton',
        'Kennedy',
        'Robinson',
    ],
    'Austria': [
        'Baumgartner',
        'Hundertwasser',
        'Fiser',
        'Weinheber',
        'Au',
        'Andris',
        'Faymann',
        'Müller',
        'Auer',
        'Rainer',
    ],
    'Belgium': [
        'Eylenbosch',
        'De Maseneer',
        'Vermeulen',
        'Debruyne',
        'Van Den Bossche',
        'De Rooms',
        'Hoste',
        'Eylenbosch',
        'Descamps',
        'Van Roy',
    ],
    'Brazil': [
        'Alvarez de Matos',
        'Lima Câmara',
        'Guimarães Bosco',
        'Sato Furtado',
        'Amorim Guimarães',
        'Vidal Alves',
        'Leal Vieira',
        'Simões Machado',
        'Luz Garcia',
        'Medina Delchiaro',
    ]
};

export const firstName = {
    'Albania': [
        'Noel',
        'Joel',
        'Mateo',
        'Ergi',
        'Luis',
        'Aron',
        'Samuel',
        'Roan',
        'Roel',
        'Xhoel'
    ],
    'Algeria': [
        'Mohamed',
        'Abdelkader',
        'Ahmed',
        'Mohammed',
        'Ali',
        'Rachid',
        'Said',
        'Brahim',
        'Omar',
        'Djamel'
    ],
    'Argentina': [
        'Santiago',
        'Mateo',
        'Juan',
        'Matías',
        'Nicolás',
        'Benjamín',
        'Pedro',
        'Tomás',
        'Thiago',
    ],
    'Australia': [
        'Oliver',
        'William',
        'Jack',
        'Noah',
        'Thomas',
        'Lucas',
        'James',
        'Alex',
        'Alexander',
        'Ethan',
    ],
    'Austria': [
        'Lukas',
        'Maximilian',
        'Jakob',
        'David',
        'Tobias',
        'Paul',
        'Jonas',
        'Felix',
        'Alexander',
        'Elias',
    ],
    'Azerbaijan': [
        'Yusif',
        'Ali',
        'Omar',
        'Huseyn',
        'Mahammad',
        'Murad',
        'Aykhan',
        'Ughur',
        'Ibrahim',
        'Tunar',
    ],
    'Belgium': [
        'Lucas',
        'Louis',
        'Noah',
        'Nathan',
        'Adam',
        'Arthur',
        'Mohamed',
        'Victor',
        'Mathis',
        'Liam',
    ],
    'Brazil': [
        'Miguel',
        'Arthur',
        'Davi',
        'Heitor',
        'Gabriel',
        'Bernardo',
        'Lorenzo',
        'João',
        'Miguel',
        'Enzo',
        'Gabriel',
        'Pedro',
        'Henrique',
    ]
};

export const MORALES = [
    'Horrible',
    'Terrible',
    'Poor',
    'Bad',
    'Normal',
    'Good',
    'Great',
    'Excellent',
    'Perfect'
];