export * from "./firstname";
export * from "./lastname";

export const teamNames = [
    'ManUnited',
    'ManCity',
    'Arsenal',
    'Chelsea',
    'Tottenham',
    'Liverpool',
    'WestHam',
    'Leicester',
    'Barcelona',
    'R.Madrid',
    'Atletico',
    'Sevilla',
    'Villareal',
    'Bayern',
    'Dortmund',
    'Schalke04',
    'Leverkusen',
    'Juventus',
    'A.C.Milan',
    'Roma',
    'Inter',
    'Napoli',
    'PSG',
    'Lazio',
    'Fiorentina',
    'Lyonnais',
    'Marseille',
    'Monaco',
    'Shakhtar',
    'DinamoKiev',
    'Benfica',
    'Porto',
    'Sporting',
    'Ajax',
    'Feyenoord',
    'PSV',
    'Galatasaray',
    'Besiktas',
    'Fenerbahce',
    'Celtic',
    'Anderlecht',
    'Wolfsburg',
    'Valencia',
    'Basel',
    'Olympiacos'
];

export const countries = [
    'Albania',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaijan',
    // 'Belarus',
    'Belgium',
    // 'Bolivia',
    // 'Bosnia',
    'Brazil',
    'Bulgaria',
    // 'Cameroon',
    // 'Chile',
    'China',
    'Colombia',
    // 'Costa Rica',
    // 'Cote d’Ivoire',
    'Croatia',
    // 'Cuba',
    'Czech Republic',
    'Denmark',
    // 'Ecuador',
    'England',
    'Egypt',
    // 'Finland',
    'France',
    // 'Georgia',
    'Germany',
    // 'Ghana',
    'Greece',
    // 'Guatemala',
    // 'Honduras',
    // 'Hungary',
    // 'Iceland',
    'Iran',
    'Iraq',
    // 'Ireland',
    // 'Israel',
    'Italy',
    // 'Jamaica',
    'Japan',
    // 'Kazakhstan',
    // 'Kenya',
    'KoreaSouth',
    // 'Kosovo',
    // 'Latvia',
    // 'Mali',
    'Mexico',
    // 'Montenegro',
    'Morocco',
    'Netherlands',
    // 'New Zealand',
    'Nigeria',
    // 'Norway',
    // 'Panama',
    // 'Paraguay',
    // 'Peru',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Saudi Arabia',
    // 'Senegal',
    'Serbia',
    // 'Slovakia',
    // 'Slovenia',
    // 'South Africa',
    'Spain',
    'Sweden',
    'Switzerland',
    'Tunisia',
    'Turkey',
    'Ukraine',
    'UAE',
    'USA',
    'Uruguay',
    // 'Uzbekistan',
    // 'Venezuela'
];

export const MORALES = [
    'Horrible',
    'Terrible',
    'Poor',
    'Bad',
    'Normal',
    'Good',
    'Great',
    'Excellent',
    'Perfect'
];