export const teamNames = [
    'ManUnited',
    'ManCity',
    'Arsenal',
    'Chelsea',
    'Tottenham',
    'Liverpool',
    'WestHam',
    'Leicester',
    'Barcelona',
    'R.Madrid',
    'Atletico',
    'Sevilla',
    'Villareal',
    'Bayern',
    'Dortmund',
    'Schalke04',
    'Leverkusen',
    'Juventus',
    'A.C.Milan',
    'Roma',
    'Inter',
    'Napoli',
    'PSG',
    'Lazio',
    'Fiorentina',
    'Lyonnais',
    'Marseille',
    'Monaco',
    'Shakhtar',
    'DinamoKiev',
    'Benfica',
    'Porto',
    'Sporting',
    'Ajax',
    'Feyenoord',
    'PSV',
    'Galatasaray',
    'Besiktas',
    'Fenerbahce',
    'Celtic',
    'Anderlecht',
    'Wolfsburg',
    'Valencia',
    'Basel',
    'Olympiacos'
];

export const countries = [
    'Albania',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaijan',
    // 'Belarus',
    'Belgium',
    // 'Bolivia',
    // 'Bosnia',
    'Brazil',
    // 'Bulgaria',
    // 'Cameroon',
    // 'Chile',
    'China',
    // 'Colombia',
    // 'Costa Rica',
    // 'Cote d’Ivoire',
    // 'Croatia',
    // 'Cuba',
    // 'Czech Republic',
    // 'Denmark',
    // 'Ecuador',
    'England',
    'Egypt',
    // 'Finland',
    'France',
    // 'Georgia',
    'Germany',
    // 'Ghana',
    'Greece',
    // 'Guatemala',
    // 'Honduras',
    // 'Hungary',
    // 'Iceland',
    'Iran',
    'Iraq',
    // 'Ireland',
    // 'Israel',
    'Italy',
    // 'Jamaica',
    'Japan',
    // 'Kazakhstan',
    // 'Kenya',
    'KoreaSouth',
    // 'Kosovo',
    // 'Latvia',
    // 'Mali',
    'Mexico',
    // 'Montenegro',
    // 'Morocco',
    // 'Netherlands',
    // 'New Zealand',
    'Nigeria',
    // 'Norway',
    // 'Panama',
    // 'Paraguay',
    // 'Peru',
    // 'Poland',
    'Portugal',
    'Qatar',
    // 'Romania',
    'Russia',
    'Saudi Arabia',
    // 'Senegal',
    // 'Serbia',
    // 'Slovakia',
    // 'Slovenia',
    // 'South Africa',
    'Spain',
    // 'Sweden',
    // 'Switzerland',
    // 'Tunisia',
    'Turkey',
    // 'Ukraine',
    'UAE',
    'USA',
    // 'Uruguay',
    // 'Uzbekistan',
    // 'Venezuela'
];

export const lastName = {
    'Azerbaijan': [
        'Mammadov',
        'Aliyev',
        'Hasanov',
        'Huseynov',
        'Guliyev',
        'Hajiyev',
        'Rasulov',
        'Suleymanov',
        'Musayev',
        'Abbasov',
        'Babayev',
        'Valiyev',
        'Orujov',
        'Ismayilov',
        'Ibrahimov',
    ],
    'England': [
        'Powell',
        'Lawrence',
        'Fox',
        'Bradley',
        'Burton',
        'Russell',
        'Marshall',
        'Sutton',
        'Turner',
        'Davis',
        'Ball',
        'Cook',
        'Moss',
        'Thomas',
        'Cunningham',
        'West',
        'Morgan',
        'Roberts',
        'Holland',
        'Davies',
    ],
    'USA': [
        'Hamilton',
        'Taylor',
        'Price',
        'Howard',
        'Simpson',
        'Griffin',
        'Logan',
        'Terrell',
        'Schwartz',
        'Fry',
        'Grant',
        'George',
        'Bennett',
        'Campbell',
        'Nicholson',
        'Myers',
        'Montoya',
        'Jackson',
        'Cross',
        'Wilcox',
    ],
    'China': [
        'Qiang',
        'Ling',
        'Xuegang',
        'Li',
        'Yating',
        'ZhenKang',
        'Jun',
        'Shuren',
        'Bo',
        'Yu',
        'Qiang',
        'Long',
        'Delan',
        'Wei',
        'Ruogang',
        'Yang',
        'Meng',
        'Xinyue',
        'Shi',
        'Qing',

    ],
    'Greece': [
        'Constantinos',
        'Macris',
        'Maragos',
        'Sannas',
        'Andreadis',
        'Boosalis',
        'Anagnos',
        'Christodoulos',
        'Tavoularis',
        'Callis',
        'Makos',
        'Sicas',
        'Constantinides',
        'Stathopoulos',
        'Demetrios',
        'Garis',
        'Katsaros',
        'Georgopoulos',
        'Grivas',
        'Spinos',
    ],
    'Albania': [
        'Agani',
        'Ajeti',
        'Bajramovic',
        'Bardici',
        'Bejko',
        'Ciftja',
        'Culaj',
        'Dedej',
        'Dreshaj',
        'Elezi',
        'Fazliu',
        'Galica',
        'Gecaj',
        'Halili',
        'Hamza',
        'Hasani',
        'Haxhiu',
        'Meshkalla',
        'Rexhepi',
        'Rugova',
        'Salihu',
        'Shulku',
        'Simaku',
    ],
    'Algeria': [
        'Alloula',
        'Boutella',
        'Djermouni',
        'Khalef',
        'Benlabed',
        'Litim',
        'Belghoul',
        'Benyamina',
        'Partyka',
        'Mammeri',
    ],
    'Argentina': [
        'Toscano',
        'Russo',
        'Iadanza',
        'Benítez',
        'Manfrin',
        'Ávila',
        'Toledo',
        'Núñez',
        'Ferrari',
        'Lucciano',
    ],
    'Australia': [
        'Jackman',
        'Clark',
        'McKenzie',
        'Bishop',
        'Mitchell',
        'Simpson',
        'Ward',
        'Hamilton',
        'Kennedy',
        'Robinson',
    ],
    'Austria': [
        'Baumgartner',
        'Hundertwasser',
        'Fiser',
        'Weinheber',
        'Au',
        'Andris',
        'Faymann',
        'Müller',
        'Auer',
        'Rainer',
    ],
    'Belgium': [
        'Eylenbosch',
        'De Maseneer',
        'Vermeulen',
        'Debruyne',
        'Van Den Bossche',
        'De Rooms',
        'Hoste',
        'Eylenbosch',
        'Descamps',
        'Van Roy',
    ],
    'Brazil': [
        'Alvarez de Matos',
        'Lima Câmara',
        'Guimarães Bosco',
        'Sato Furtado',
        'Amorim Guimarães',
        'Vidal Alves',
        'Leal Vieira',
        'Simões Machado',
        'Luz Garcia',
        'Medina Delchiaro',
    ],
    'France': [
        'Arsenault',
        'Bazalgette',
        'De Saint-Pierre',
        'Leclair',
        'Didier',
        'Dieudonné',
        'Masson',
        'Ballesdens',
        'Deshaies',
        'Fétique',
    ],
    'Germany': [
        'Haselrieder',
        'Bechtold',
        'Stromberg',
        'Hasselhoff',
        'Pasche',
        'Theismann',
        'Engelberg',
        'Seidl',
        'Fleischman',
        'Kleinheisterkamp',
    ],
    'Italy': [
        'De Filippis',
        'Zinno',
        'Avellino',
        'Audino',
        'Pennino',
        'Micale',
        'Covino',
        'Bonomo',
        'Fata',
        'Terrano',
    ],
    'Iran': [
        'Yazdani',
        'Mehrnia',
        'Yekta',
        'Azari',
        'Khalili',
        'Nemati',
        'Eghbali',
        'Taghipour',
        'Asayesh',
        'Dehghan',
        'Sobhani',
        'Panahi',
        'Moshiri',
        'Miri',
        'Bahadori',
        'Tajik',
        'Soleymani',
        'Torabi',
        'Kashkouli',
        'Kamran',
    ],
    'Turkey': [
        'Yildizeli',
        'Bucak',
        'Sevim',
        'Altan',
        'Sezen',
        'Uslu',
        'Gursu',
        'Kubat',
        'Zaimoglu',
        'Akbulut',
        'Egemen',
        'Simsek',
        'Koz',
        'Emre',
        'Yakut',
        'Guclu',
        'Basturk',
        'Turkyilmaz',
        'Karabulut',
        'Karatay',
    ],
    'Japan': [
        'Yoshii',
        'Shizue',
        'Toshitsugu',
        'Ikku',
        'Toshikuni',
        'Nobuyori',
        'Iesada',
        'Shintaro',
        'Akihiro',
        'Hirokumi',
        'Haruhiro',
        'Aki',
        'Norihide',
        'Yoshinaka',
        'Hirotada',
        'Sojuro',
        'Kyoden',
        'Hoshi',
        'Katsumi',
        'Motoshige',
    ],
    'KoreaSouth': [
        'Hyonjun',
        'Young-Ja',
        'Jong-Yeol',
        'Yong-Chol',
        'Jun-Seo',
        'Seong-Gi',
        'Chong-Yol',
        'Min-Hyuk',
        'Tohyon',
        'Kwang',
        'Ji-Hu',
        'Dong-Sun',
        'Song-Su',
        'Kwang-Hyok',
        'Joon-Ho',
        'Seong',
        'Suk-Chul',
        'Pyong-Ho',
        'Young-Soo',
        'Do-Hyeon',
    ],
    'Iraq': ['el-Zamani',
        'al-Masood',
        'al-Qazi',
        'al-Mahfouz',
        'al-Haider',
        'el-Akbar',
        'el-Ahsan',
        'el-Sala',
        'el-Malik',
        'al-Tawil',
        'al-Shabazz',
        'al-Faraj',
        'el-Nasser',
        'el-Uddin',
        'al-Baddour',
        'el-Abdella',
        'al-Qazi',
        'el-Popal',
        'el-Akbari',
        'al-Zadeh',
        'el-Salih',
        'al-Massoud',
        'al-Soliman',
        'el-Rassi',
        'al-Zamani',
        'al-Abid',
        'el-Bahri',
        'el-Shareef',
        'el-Hatem',
        'al-Abbasi',],
    'Saudi Arabia': ['el-Zamani',
        'al-Masood',
        'al-Qazi',
        'al-Mahfouz',
        'al-Haider',
        'el-Akbar',
        'el-Ahsan',
        'el-Sala',
        'el-Malik',
        'al-Tawil',
        'al-Shabazz',
        'al-Faraj',
        'el-Nasser',
        'el-Uddin',
        'al-Baddour',
        'el-Abdella',
        'al-Qazi',
        'el-Popal',
        'el-Akbari',
        'al-Zadeh',
        'el-Salih',
        'al-Massoud',
        'al-Soliman',
        'el-Rassi',
        'al-Zamani',
        'al-Abid',
        'el-Bahri',
        'el-Shareef',
        'el-Hatem',
        'al-Abbasi',],
    'Qatar': ['el-Zamani',
        'al-Masood',
        'al-Qazi',
        'al-Mahfouz',
        'al-Haider',
        'el-Akbar',
        'el-Ahsan',
        'el-Sala',
        'el-Malik',
        'al-Tawil',
        'al-Shabazz',
        'al-Faraj',
        'el-Nasser',
        'el-Uddin',
        'al-Baddour',
        'el-Abdella',
        'al-Qazi',
        'el-Popal',
        'el-Akbari',
        'al-Zadeh',
        'el-Salih',
        'al-Massoud',
        'al-Soliman',
        'el-Rassi',
        'al-Zamani',
        'al-Abid',
        'el-Bahri',
        'el-Shareef',
        'el-Hatem',
        'al-Abbasi',],
    'UAE': ['el-Zamani',
        'al-Masood',
        'al-Qazi',
        'al-Mahfouz',
        'al-Haider',
        'el-Akbar',
        'el-Ahsan',
        'el-Sala',
        'el-Malik',
        'al-Tawil',
        'al-Shabazz',
        'al-Faraj',
        'el-Nasser',
        'el-Uddin',
        'al-Baddour',
        'el-Abdella',
        'al-Qazi',
        'el-Popal',
        'el-Akbari',
        'al-Zadeh',
        'el-Salih',
        'al-Massoud',
        'al-Soliman',
        'el-Rassi',
        'al-Zamani',
        'al-Abid',
        'el-Bahri',
        'el-Shareef',
        'el-Hatem',
        'al-Abbasi',],
    'Egypt': [
        'Ganim',
        'Bitar',
        'Sarkis',
        'Attia',
        'Asfour',
        'Daher',
        'Kattan',
        'Halabi',
        'Malouf',
        'Assaf',
        'Shadid',
        'Essa',
        'Khouri',
        'Saliba',
        'Isa',
        'Sabbagh',
        'Arian',
        'Kouri',
        'Totah',
        'Tuma',
    ],
    'Spain': [
        'Céspedes',
        'Sanz',
        'Pliego',
        'Cortés',
        'Arnal',
        'Sáez',
        'Atenas',
        'Mastache',
        'Molina',
        'Botín',
        'Indiano',
        'García',
        'Cadaval',
        'Fernán',
        'Lain',
        'Arias',
        'Rubio',
        'Moya',
        'Velázquez',
        'Juderías',
    ],
    'Mexico': [
        'Céspedes',
        'Sanz',
        'Pliego',
        'Cortés',
        'Arnal',
        'Sáez',
        'Atenas',
        'Mastache',
        'Molina',
        'Botín',
        'Indiano',
        'García',
        'Cadaval',
        'Fernán',
        'Lain',
        'Arias',
        'Rubio',
        'Moya',
        'Velázquez',
        'Juderías',
    ],
    'Portugal': [
        'Corte-Real',
        'Pascoal',
        'Castro',
        'Rodrigues',
        'Vila',
        'Furtado',
        'Andrade',
        'Agostinho',
        'Valente',
        'Fernandes',
        'Montenegro',
        'Antunes',
        'Vila',
        'Cardoso',
        'Antunes',
        'Gusmão',
        'Vieira',
        'Alcantara',
        'Tomás',
        'Albuquerque',
    ],
    'Russia': [
        'Savelievich',
        'Yermolayevich',
        'Filippovich',
        'Olegovich',
        'Maximovich',
        'Pavlovich',
        'Maximovich',
        'Vitalievich',
        'Timurovich',
        'Grigorievich',
        'Stepanovich',
        'Yevgenievich',
        'Valentinovich',
        'Maximovich',
        'Sergeyevich',
        'Yurievich',
        'Rostislavovich',
        'Zakharovich',
        'Valerianovich',
        'Kirillovich',
    ],
    'Nigeria': [
        'Chidike',
        'Zebenjo',
        'Okeke',
        'Uchey',
        'Chika',
        'Amadi',
        'Oby',
        'Orjy',
        'Chineze',
        'Chinwendu',
        'Ifeanyichukwu',
        'Tobechukwu',
        'Orjie',
        'Afamefula',
        'Chinuah',
        'Halim',
        'Akubundu',
        'Mazzi',
        'Chydi',
        'Ngozi',
    ]
};

export const firstName = {
    'Albania': [
        'Noel',
        'Joel',
        'Mateo',
        'Ergi',
        'Luis',
        'Aron',
        'Samuel',
        'Roan',
        'Roel',
        'Xhoel'
    ],
    'England': [
        'Vincent',
        'Kai',
        'Frankie',
        'Nico',
        'Calvin',
        'Arlo',
        'Teddie',
        'Kieran',
        'Adam',
        'Freddy',
        'Harrison',
        'Daniel',
        'Quinn',
        'Hugh',
        'Rufus',
        'Raphael',
        'Raphael',
        'Maxwell',
        'Bradley',
        'Maximilian',
    ],
    'USA': [
        'Joseph',
        'Charles',
        'Frankie',
        'Max',
        'Charlie',
        'Tyson',
        'Rogelio',
        'Darius',
        'Byron',
        'Kolby',
        'Bailey',
        'Aaron',
        'Ryan',
        'Callum',
        'Reece',
        'Jonathan',
        'Jasper',
        'Nehemiah',
        'Braeden',
        'Titus',
    ],
    'China': [
        'Xiang',
        'Wu',
        'Zhao',
        'Liu',
        'Xiong',
        'Li',
        'Feng',
        'Sun',
        'Yang',
        'Xiao',
        'Zou',
        'Lai',
        'Zeng',
        'Bai',
        'Liu',
        'Xian',
        'Geng',
        'Kong',
        'Wan',
        'Xiang',
    ],
    'Greece': [
        'Haris',
        'Iasonas',
        'Aristotelis',
        'Aristidis',
        'Panikos',
        'Serapheim',
        'Stergios',
        'Eros',
        'Iordanis',
        'Myron',
        'Vassilios',
        'Miron',
        'Periklis',
        'Aggelos',
        'Yorgos',
        'Prokopos',
        'Minos',
        'Kiriakos',
        'Spiro',
        'Lambros',
    ],
    'Russia': [
        'Fomin',
        'Konyakov',
        'Kubyshkin',
        'Grekov',
        'Ryzhanov',
        'Khodyayev',
        'Ilyushin',
        'Rabrenovich',
        'Polachev',
        'Yumashev',
        'Dernov',
        'Balakirev',
        'Annikov',
        'Chupakhin',
        'Savasin',
        'Pokrovsky',
        'Belinsky',
        'Glukhov',
        'Kirilishen',
        'Koshelev',
    ],
    'Algeria': [
        'Mohamed',
        'Abdelkader',
        'Ahmed',
        'Mohammed',
        'Ali',
        'Rachid',
        'Said',
        'Brahim',
        'Omar',
        'Djamel'
    ],
    'Argentina': [
        'Santiago',
        'Mateo',
        'Juan',
        'Matías',
        'Nicolás',
        'Benjamín',
        'Pedro',
        'Tomás',
        'Thiago',
    ],
    'Australia': [
        'Oliver',
        'William',
        'Jack',
        'Noah',
        'Thomas',
        'Lucas',
        'James',
        'Alex',
        'Alexander',
        'Ethan',
    ],
    'Austria': [
        'Lukas',
        'Maximilian',
        'Jakob',
        'David',
        'Tobias',
        'Paul',
        'Jonas',
        'Felix',
        'Alexander',
        'Elias',
    ],
    'Azerbaijan': [
        'Yusif',
        'Ali',
        'Omar',
        'Huseyn',
        'Mahammad',
        'Murad',
        'Aykhan',
        'Ughur',
        'Ibrahim',
        'Tunar',
    ],
    'Belgium': [
        'Lucas',
        'Louis',
        'Noah',
        'Nathan',
        'Adam',
        'Arthur',
        'Mohamed',
        'Victor',
        'Mathis',
        'Liam',
    ],
    'Brazil': [
        'Miguel',
        'Arthur',
        'Davi',
        'Heitor',
        'Gabriel',
        'Bernardo',
        'Lorenzo',
        'João',
        'Miguel',
        'Enzo',
        'Gabriel',
        'Pedro',
        'Henrique',
    ],
    'France': [
        'Ladislas ',
        'Constantin ',
        'Basile',
        'Émilien ',
        'Jean-Guy ',
        'Timothé ',
        'Fabien ',
        'Constantin ',
        'Maxime ',
        'Samuel ',
    ],
    'Germany': [
        'Tizian',
        'Nils',
        'Steffen',
        'Gert',
        'Oskar',
        'Cäsar',
        'Meik',
        'Gunter',
        'Maximilian',
        'Ruprecht',
    ],
    'Italy': [
        'Girardo',
        'Giovanni',
        'Ambrogio',
        'Marolo',
        'Elvezio',
        'Silvano',
        'Attilio',
        'Esuperio',
        'Bruto',
        'Vulpiano',
    ],
    'Iran': [
        'Amin',
        'Hossein',
        'Kazem',
        'Soroosh',
        'Peyman',
        'Mehran',
        'Amir Mohammad',
        'Changiz',
        'Behrouz',
        'Sirvan',
        'Homayoun',
        'Qobad',
        'Sahand',
        'Mamad',
        'Vahid',
        'Rostam',
        'Benyamin',
        'Mehdi',
        'Yashar',
        'Latif',
    ],
    'Turkey': [
        'Eraydin',
        'Alpar',
        'Tumkor',
        'Seda',
        'Ali Riza',
        'Okay',
        'Tor',
        'Apak',
        'Tozun',
        'Soylu',
        'Ergor',
        'Uzay',
        'Erdener',
        'Dinc',
        'Ayyildiz',
        'Vedat',
        'Kaner',
        'Tezal',
        'Goktug',
        'Hayri',
    ],
    'Japan': [
        'Hirota',
        'Kurosawa',
        'Kawamura',
        'Murano',
        'Hino',
        'Sakane',
        'Hori',
        'Yoshikawa',
        'Edamitsu',
        'Komuro',
        'Seto',
        'Hashi',
        'Saito',
        'Amari',
        'Sanda',
        'Fujimura',
        'Ishikura',
        'Kawada',
        'Oshita',
        'Shinsato',
    ],
    'KoreaSouth': [
        'Sa',
        'Chon',
        'Song',
        'Choe',
        'Kong',
        'Mangjol',
        'Chang',
        'In',
        'Ryuk',
        'Pu',
        'Chegal',
        'Yu',
        'Park',
        'Sonu',
        'Yang',
        'Tang',
        'Chu',
        'Kum',
        'Che',
        'Kum',
    ],
    'Iraq': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Saudi Arabia': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Qatar': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'UAE': ['Tareef',
        'Zuraara',
        'Jaad',
        'Bishr',
        'Mudrik',
        'Ashraf',
        'Umair',
        'Munsif',
        'Luqmaan',
        'Mahdi',
        'Ameen',
        'Naseem',
        'Muhammad',
        'Abdul Wahaab',
        'Abdul Kareem',
        'Abdul Baasid',
        'Alawi',
        'Sakeen',
        'Usaama',
        'Mushtaaq',
        'Sabaah',
        'Murshid',
        'Zayyaan',
        'Qutb',
        'Abdul Wadood',
        'Shabaan',
        'Adeeb',
        'Razeen',
        'Abdul Haleem',
        'Nassaar',],
    'Egypt': [
        'Ahmad',
        'Kafele',
        'Nader',
        'Abdelrahman',
        'Nassor',
        'Assem',
        'Mahmoud',
        'Barika',
        'Bebti',
        'Hassan',
        'Adham',
        'Mamdoh',
        'Marwan',
        'Hosni',
        'Karim',
        'Aymn',
        'Aly',
        'Kamuzu',
        'Ismael',
    ],
    'Spain': [
        'Gael',
        'Franco',
        'Zacarías',
        'Saúl',
        'Macos',
        'Eduard',
        'Jonathan',
        'Christian',
        'Samuel',
        'Iker',
        'Alfredo',
        'Luis',
        'Nicolás',
        'Jose',
        'Mauric',
        'Lautaro',
        'Aaron',
        'Vicent',
        'Emiliano',
        'Juan',
    ],
    'Mexico': [
        'Gael',
        'Franco',
        'Zacarías',
        'Saúl',
        'Macos',
        'Eduard',
        'Jonathan',
        'Christian',
        'Samuel',
        'Iker',
        'Alfredo',
        'Luis',
        'Nicolás',
        'Jose',
        'Mauric',
        'Lautaro',
        'Aaron',
        'Vicent',
        'Emiliano',
        'Juan',
    ],
    'Portugal': [
        'Fred',
        'Leopoldo',
        'Gustavo',
        'André',
        'Ernesto',
        'Artur',
        'Heliodoro',
        'Ismael',
        'Rogério',
        'Tadeu',
        'Feliciano',
        'Isaac',
        'Ângelo',
        'Luís',
        'Victor',
        'Cristóvão',
        'Régulo',
        'Raul',
        'Kévim',
        'Noah',
    ],
    'Nigeria': [
        'Yobachukwu',
        'Chydi',
        'Nkechi',
        'Ebele',
        'Jaja',
        'Okparra',
        'Madukaife',
        'Ugoorji',
        'Uwaezuoke',
        'Ijendu',
        'Okpara',
        'Uzochi',
        'Okeke',
        'Chydea',
        'Okparra',
        'Chimaijem',
        'Chikere',
        'Chidiebere',
        'Chidey',
        'Madu',
    ]
};


export const MORALES = [
    'Horrible',
    'Terrible',
    'Poor',
    'Bad',
    'Normal',
    'Good',
    'Great',
    'Excellent',
    'Perfect'
];